name: AudioMixer
options:
  bundleIdPrefix: com.github.piasy
targets:
  AudioMixerExample:
    type: application
    platform: iOS
    deploymentTarget: "9.0"
    sources:
      - example
    settings:
      INFOPLIST_FILE: "example/Info.plist"
      ENABLE_BITCODE: "NO"
      SYSTEM_HEADER_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/../libs/ffmpeg/include $(PROJECT_DIR)/../libs/webrtc/include"
    dependencies:
      - target: AudioMixer
  AudioMixer:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources:
      - ../src
      - ../generated_src/cpp
      - ../generated_src/objc
      - path: ../djinni/support-lib/djinni_common.hpp
        type: file
      - path: ../djinni/support-lib/proxy_cache_interface.hpp
        type: file
      - path: ../djinni/support-lib/proxy_cache_impl.hpp
        type: file
      - path: ../djinni/support-lib/objc
    settings:
      ENABLE_BITCODE: "NO"
      SYSTEM_HEADER_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/../libs/ffmpeg/include $(PROJECT_DIR)/../libs/webrtc/include"
      USER_HEADER_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/../libs/ffmpeg/include $(PROJECT_DIR)/../libs/webrtc/include $(PROJECT_DIR)/../djinni/support-lib $(PROJECT_DIR)/../djinni/support-lib/objc $(PROJECT_DIR)/../generated_src/cpp $(PROJECT_DIR)/../generated_src/objc $(PROJECT_DIR)/../src"
      LIBRARY_SEARCH_PATHS: "$(inherited) $(PROJECT_DIR)/../libs/webrtc/lib/iOS $(PROJECT_DIR)/../libs/ffmpeg/lib/iOS"
      OTHER_CFLAGS: "$(inherited) -DWEBRTC_POSIX -DWEBRTC_IOS"
      OTHER_LDFLAGS: "$(inherited) -lz -lbz2 -liconv -lwebrtc -lswresample -lavformat -lavcodec -lavutil -framework CoreMedia -framework CoreVideo -framework VideoToolbox -framework AudioToolbox"
